### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by thomased** [thomased/spectra.visual#1]
- [ ] more specs
- [ ] common names, for searching
- [ ] richer taxonomic data, for searching
- [ ] better search (fuzzy matching of arbitrary input)
- [ ] per-species file formatting for broad compatability (mica)
